steps:
  - name: gcr.io/cloud-builders/docker
    dir: welcome-to-docker
    script: >
      docker build -t
      europe-west3-docker.pkg.dev/coen-danial-dehkordi/stella-repo/welcome-to-docker
      .
    automapSubstitutions: true
images:
  - >-
    europe-west3-docker.pkg.dev/coen-danial-dehkordi/stella-repo/welcome-to-docker
options:
  logging: CLOUD_LOGGING_ONLY
